removed Norwegian import_for_ws_tests script

diff --git a/docker/import_for_ws_tests b/docker/import_for_ws_tests
--- a/docker/import_for_ws_tests
+++ b/docker/import_for_ws_tests
@@ -58,17 +58,17 @@ do_setup
 ### LEXDATA PATHS
 
 SVLEX=sv_se_nst_lex.db
-NOBLEX=no_nob_nst_lex.db
+#NOBLEX=no_nob_nst_lex.db
 AMELEX=en_am_cmu_lex.db
 ARLEX=ar_ar_tst_lex.db
 if [ -e $APPDIR/db_files/$SVLEX ]; then
     echo "[$CMD] cannot create db if it already exists: $LOCALDIR/db_files/$SVLEX" >&2
     exit 1
 fi
-if [ -e $APPDIR/db_files/$NOBLEX ]; then
-    echo "[$CMD] cannot create db if it already exists: $LOCALDIR/db_files/$NOBLEX" >&2
-    exit 1
-fi
+#if [ -e $APPDIR/db_files/$NOBLEX ]; then
+#    echo "[$CMD] cannot create db if it already exists: $LOCALDIR/db_files/$NOBLEX" >&2
+#    exit 1
+#fi
 if [ -e $APPDIR/db_files/$AMELEX ]; then
     echo "[$CMD] cannot create db if it already exists: $LOCALDIR/db_files/$AMELEX" >&2
     exit 1
@@ -119,19 +119,19 @@ else
     exit 1
 fi
 
-echo "" >&2
-echo "IMPORT: $NOBLEX" >&2
-if createEmptyDB $APPDIR/db_files/$NOBLEX ; then
-    if zcat $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.gz | head -1000 > $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing && importLex $APPDIR/db_files/$NOBLEX nb-no.nst $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing nb-no_ws-sampa $APPDIR/symbol_sets ; then
-	echo -n ""
-    else
-	echo "$NOBLEX FAILED" >&2
-	exit 1
-    fi
-else
-    echo "$NOBLEX FAILED" >&2
-    exit 1
-fi
+# echo "" >&2
+# echo "IMPORT: $NOBLEX" >&2
+# if createEmptyDB $APPDIR/db_files/$NOBLEX ; then
+#     if zcat $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.gz | head -1000 > $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing && importLex $APPDIR/db_files/$NOBLEX nb-no.nst $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing nb-no_ws-sampa $APPDIR/symbol_sets ; then
+# 	echo -n ""
+#     else
+# 	echo "$NOBLEX FAILED" >&2
+# 	exit 1
+#     fi
+# else
+#     echo "$NOBLEX FAILED" >&2
+#     exit 1
+# fi
 
 echo "" >&2
 echo "IMPORT: $AMELEX" >&2
