docker

diff --git a/docker/import_all_light b/docker/import_all_light
--- a/docker/import_all_light
+++ b/docker/import_all_light
@@ -108,7 +108,12 @@ echo "" >&2
 echo "IMPORT: $SVLEX" >&2
 
 if createEmptyDB $APPDIR/db_files/$SVLEX ; then
-    zcat $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.gz | head -50000 > $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.lightweight && importLex $APPDIR/db_files/$SVLEX sv-se.nst $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.lightweight sv-se_ws-sampa $APPDIR/symbol_sets
+    if zcat $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.gz | head -50000 > $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.lightweight && importLex $APPDIR/db_files/$SVLEX sv-se.nst $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.lightweight sv-se_ws-sampa $APPDIR/symbol_sets ; then
+	echo -n ""
+    else
+	echo "$SVLEX FAILED" >&2
+	exit 1
+    fi
 else
     echo "$SVLEX FAILED" >&2
     exit 1
@@ -117,7 +122,12 @@ fi
 echo "" >&2
 echo "IMPORT: $NOBLEX" >&2
 if createEmptyDB $APPDIR/db_files/$NOBLEX ; then
-        zcat $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.gz | head -50000 > $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.lightweight && importLex $APPDIR/db_files/$NOBLEX nb-no.nst $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.lightweight nb-no_ws-sampa $APPDIR/symbol_sets
+    if zcat $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.gz | head -50000 > $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.lightweight && importLex $APPDIR/db_files/$NOBLEX nb-no.nst $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.lightweight nb-no_ws-sampa $APPDIR/symbol_sets ; then
+	echo -n ""
+    else
+	echo "$NOBLEX FAILED" >&2
+	exit 1
+    fi
 else
     echo "$NOBLEX FAILED" >&2
     exit 1
@@ -126,7 +136,12 @@ fi
 echo "" >&2
 echo "IMPORT: $AMELEX" >&2
 if createEmptyDB $APPDIR/db_files/$AMELEX ; then 
-    importLex $APPDIR/db_files/$AMELEX en-us.cmu $APPDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8 en-us_ws-sampa $APPDIR/symbol_sets
+    if importLex $APPDIR/db_files/$AMELEX en-us.cmu $APPDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8 en-us_ws-sampa $APPDIR/symbol_sets ; then
+	echo -n ""
+    else
+	echo "$AMELEX FAILED" >&2
+	exit 1
+    fi
 else
     echo "$AMELEX FAILED" >&2
     exit 1
@@ -135,7 +150,12 @@ fi
 echo "" >&2
 echo "IMPORT: $ARLEX" >&2
 if createEmptyDB $APPDIR/db_files/$ARLEX ; then
-    importLex $APPDIR/db_files/$ARLEX ar-test $APPDIR/lexdata.git/ar/TEST/ar_TEST.pron-ws.utf8 ar_ws-sampa $APPDIR/symbol_sets
+    if importLex $APPDIR/db_files/$ARLEX ar-test $APPDIR/lexdata.git/ar/TEST/ar_TEST.pron-ws.utf8 ar_ws-sampa $APPDIR/symbol_sets ; then
+	echo -n ""
+    else
+	echo "$ARLEX FAILED" >&2
+	exit 1
+    fi
 else
     echo "$ARLEX FAILED" >&2
     exit 1
