docker import script

diff --git a/docker/import_all b/docker/import_all
--- a/docker/import_all
+++ b/docker/import_all
@@ -11,7 +11,7 @@ if [ $# -ne 2 ]; then
 	echo "
 USAGE: sh $CMD <APPDIR_IN_DOCKER> <APPDIR_ON_DISK>
 
-Imports lexicon data for Swedish, Norwegian, US English and a small test file for Arabic.
+Imports lexicon data for Swedish, Norwegian, US English, and a small set of test data for Arabic.
 " >&2
 	exit 1
 fi
@@ -87,60 +87,59 @@ cp $APPDIR/lexdata.git/converters/*.cnv $APPDIR/symbol_sets/ || exit 1
 
 echo "" >&2
 echo "IMPORT: $SVLEX" >&2
-
-if createEmptyDB $APPDIR/db_files/$SVLEX ; then
-    if importLex $APPDIR/db_files/$SVLEX sv-se.nst sv_SE $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.gz sv-se_ws-sampa $APPDIR/symbol_sets ; then
+#if createEmptyDB $APPDIR/db_files/$SVLEX ; then
+    if importSql $APPDIR/lexdata.git/sv-se/nst/swe030224NST.pron-ws.utf8.sql.gz $APPDIR/db_files/$SVLEX ; then
 	echo -n ""
     else
 	echo "$SVLEX FAILED" >&2
 	exit 1
     fi
-else
-    echo "$SVLEX FAILED" >&2
-    exit 1
-fi
+#else
+#    echo "$SVLEX FAILED" >&2
+#    exit 1
+#fi
 
 echo "" >&2
 echo "IMPORT: $NOBLEX" >&2
-if createEmptyDB $APPDIR/db_files/$NOBLEX ; then
-    if importLex $APPDIR/db_files/$NOBLEX nb-no.nst nb_NO $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.gz nb-no_ws-sampa $APPDIR/symbol_sets ; then
+#if createEmptyDB $APPDIR/db_files/$NOBLEX ; then
+    if importSql $APPDIR/lexdata.git/nb-no/nst/nor030224NST.pron-ws.utf8.sql.gz $APPDIR/db_files/$NOBLEX ; then
 	echo -n ""
     else
 	echo "$NOBLEX FAILED" >&2
 	exit 1
     fi
-else
-    echo "$NOBLEX FAILED" >&2
-    exit 1
-fi
+#else
+#    echo "$NOBLEX FAILED" >&2
+#    exit 1
+#fi
 
 echo "" >&2
 echo "IMPORT: $AMELEX" >&2
-if createEmptyDB $APPDIR/db_files/$AMELEX ; then 
-    if importLex $APPDIR/db_files/$AMELEX en-us.cmu en_US $APPDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8 en-us_ws-sampa $APPDIR/symbol_sets ; then
+#if createEmptyDB $APPDIR/db_files/$AMELEX ; then 
+    if importSql $APPDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8.sql.gz $APPDIR/db_files/$AMELEX ; then
 	echo -n ""
     else
 	echo "$AMELEX FAILED" >&2
 	exit 1
     fi
-else
-    echo "$AMELEX FAILED" >&2
-    exit 1
-fi
+#else
+#    echo "$AMELEX FAILED" >&2
+#    exit 1
+#fi
 
 echo "" >&2
 echo "IMPORT: $ARLEX" >&2
-if createEmptyDB $APPDIR/db_files/$ARLEX ; then
-    if importLex $APPDIR/db_files/$ARLEX ar-test ar_AR $APPDIR/lexdata.git/ar/TEST/ar_TEST.pron-ws.utf8 ar_ws-sampa $APPDIR/symbol_sets ; then
+#if createEmptyDB $APPDIR/db_files/$ARLEX ; then
+    if importSql $APPDIR/lexdata.git/ar/TEST/ar_TEST.pron-ws.utf8.sql.gz $APPDIR/db_files/$ARLEX ; then
 	echo -n ""
     else
 	echo "$ARLEX FAILED" >&2
 	exit 1
     fi
-else
-    echo "$ARLEX FAILED" >&2
-    exit 1
-fi
+#else
+#    echo "$ARLEX FAILED" >&2
+#    exit 1
+#fi
 
 echo "[$CMD] Clearing lexdata cache" >&2
 rm -fr $APPDIR/lexdata.git
