docker scripts

diff --git a/docker/import_all b/docker/import_all
--- a/docker/import_all
+++ b/docker/import_all
@@ -3,6 +3,7 @@
 ## INTERNAL SCRIPT FOR USE INSIDE OF DOCKER CONTAINER
 
 CMD=`basename $0`
+scriptdir=`dirname $0`
 export GOPATH=`go env GOPATH`
 export PATH=$PATH:$GOPATH/bin
 
@@ -22,34 +23,40 @@ echo "[$CMD] APPDIR=$APPDIR" >&2
 echo "[$CMD] LOCALDIR=$LOCALDIR" >&2
 
 function do_setup {
-    if [ -d $APPDIR/symbol_sets ] ; then
-	echo "[$CMD] APPDIR <$LOCALDIR> is already configured. No setup needed." >&2
-	return
-    fi
-
-
-    if [ -z "$GOPATH" ] ; then
-	echo "[$CMD] The GOPATH environment variable is required!" >&2
+    if $scriptdir/setup ; then
+	echo "[$CMD] Setup completed" >&2
+    else
+	echo "[$CMD] Couldn't run setup" >&2
 	exit 1
     fi
-
-    ### LEXDATA PREPS
-
-    echo "[$CMD] Setting up basic files in LEXDATA dir $LOCALDIR ($APPDIR inside docker)... " >&2
-
-    mkdir -p $APPDIR || exit 1
-    mkdir -p $APPDIR/symbol_sets || exit 1
-    mkdir -p $APPDIR/db_files || exit 1
-
-    cp $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/*.sym $APPDIR/symbol_sets/ || exit 1
-    cp $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/*.cnv $APPDIR/symbol_sets/ || exit 1
-    echo "" >> $APPDIR/symbol_sets/mappers.txt || exit 1
-    cat $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/mappers.txt >> $APPDIR/symbol_sets/mappers.txt || exit 1
+    # if [ -d $APPDIR/symbol_sets ] ; then
+    # 	echo "[$CMD] APPDIR <$LOCALDIR> is already configured. No setup needed." >&2
+    # 	return
+    # fi
 
 
-    ### COMPLETED
+    # if [ -z "$GOPATH" ] ; then
+    # 	echo "[$CMD] The GOPATH environment variable is required!" >&2
+    # 	exit 1
+    # fi
 
-    echo "[$CMD] COMPLETED" >&2
+    # ### LEXDATA PREPS
+
+    # echo "[$CMD] Setting up basic files in LEXDATA dir $LOCALDIR ($APPDIR inside docker)... " >&2
+
+    # mkdir -p $APPDIR || exit 1
+    # mkdir -p $APPDIR/symbol_sets || exit 1
+    # mkdir -p $APPDIR/db_files || exit 1
+
+    # cp $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/*.sym $APPDIR/symbol_sets/ || exit 1
+    # cp $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/*.cnv $APPDIR/symbol_sets/ || exit 1
+    # echo "" >> $APPDIR/symbol_sets/mappers.txt || exit 1
+    # cat $GOPATH/src/github.com/stts-se/pronlex/lexserver/demo_files/mappers.txt >> $APPDIR/symbol_sets/mappers.txt || exit 1
+
+
+    # ### COMPLETED
+
+    # echo "[$CMD] COMPLETED" >&2
 }
 
 
