docker/setup

diff --git a/docker/setup b/docker/setup
--- a/docker/setup
+++ b/docker/setup
@@ -106,6 +106,14 @@ else
 fi
 
 echo "" >&2
+echo "IMPORT: $LEXDB:nb" >&2
+    zcat $LEXDATA/nb-no/nst/nor030224NST.pron-ws.utf8.gz | head -1000 > $LEXDATA/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing && go run $CMDDIR/importLex/importLex.go $APPDIR/db_files/$NOBLEX nb $LEXDATA/nb-no/nst/nor030224NST.pron-ws.utf8.for_testing nb-no_ws-sampa $APPDIR/symbol_sets
+else
+    echo "$NOBLEX FAILED" >&2
+    exit 1
+fi
+
+echo "" >&2
 echo "IMPORT: $LEXDB:enu" >&2
 if cat $DOCKERDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8 | egrep -wi "test|a|children" > $DOCKERDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8.for_testing && importLex $DOCKERDIR/db_files/$LEXDB enu $DOCKERDIR/lexdata.git/en-us/cmudict/cmudict-0.7b-ws.utf8.for_testing en-us_ws-sampa $DOCKERDIR/symbol_sets ; then
     echo -n ""
